---
# Install programs inside PXE image

- name: Install basic Linux utilities inside PXE image
  shell: |
    chroot /srv/live-build /bin/bash -c "
      apt-get update &&
      DEBIAN_FRONTEND=noninteractive apt-get install -y \
        tree ncdu htop curl wget git unzip vim tmux \
        net-tools build-essential
    "
  args:
    executable: /bin/bash

- name: Install high-level programs inside PXE image
  shell: |
    chroot /srv/live-build /bin/bash -c "
      DEBIAN_FRONTEND=noninteractive apt-get install -y \
        krita inkscape gimp texlive-full texmaker \
        libreoffice python3-pip python3-venv
    "
  args:
    executable: /bin/bash

